### ISSUE TITLE
Practica de consulta de datos en Visual

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipohjf#1]
El estudiante debe diseñar una App con c# para visualizar datos de una App con Visual Studio presentando un reporte de practica 8.

1. El estudiante debe tener instalado en su computadora

XAMPP con MySQL, Apache y phpAdmin
Motor de MySQL para conectar Visual Studio.
Crear una tabla estudiante en phpAdmin con los siguientes campos

1. No de control
2. Nombre
3. Apellido Paterno
4. Apellido Materno
5. Semestre
6. Correo electrónico

Realizar la consulta general de datos codificando en Visual Studio con c# utilizando el No de control para realizar una búsqueda de datos, utilizando controles como caja de texto.
Nota: El numero de control deber ser tecleado en la caja de texto y realizar una consulta en SQL para conocer si existe el no de control, en caso de no encontrar el no de control mandar un mensaje que no se encontro.
![app](https://user-images.githubusercontent.com/71857813/168120938-4f40fde5-78d1-4069-ade1-145f253b0149.png)

**Comment by FedericoVictorianoSierra** [comment]
[Practica 8 (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipohjf/files/8693864/Practica.8.Federico.Victoriano.Sierra.4US.pdf)

**Comment by JoseABCruz** [comment]
[Practica 8 (José Antonio Balbuena Cruz 4US).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipohjf/files/8694253/Practica.8.Jose.Antonio.Balbuena.Cruz.4US.pdf)

**Comment by Heidi-19** [comment]
[Practica 8 - Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-equipohjf/files/8712701/Practica.8.-.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by IrvingFernand0** [comment]
Calificación:
Heidi Lucy: 20%
Jose Antonio: 20%
Federico: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
